# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ixtopor_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(477, 479)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/if.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabCode = QtWidgets.QWidget()
        self.tabCode.setObjectName("tabCode")
        self.textEdit = QtWidgets.QTextEdit(self.tabCode)
        self.textEdit.setGeometry(QtCore.QRect(10, 40, 291, 261))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("font: 10pt \"MS Gothic\";")
        self.textEdit.setObjectName("textEdit")
        self.progressBar = QtWidgets.QProgressBar(self.tabCode)
        self.progressBar.setGeometry(QtCore.QRect(9, 365, 431, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.btnPlayPause = QtWidgets.QToolButton(self.tabCode)
        self.btnPlayPause.setGeometry(QtCore.QRect(69, 10, 25, 19))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/play_pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPlayPause.setIcon(icon1)
        self.btnPlayPause.setObjectName("btnPlayPause")
        self.btn_Forward = QtWidgets.QToolButton(self.tabCode)
        self.btn_Forward.setGeometry(QtCore.QRect(100, 10, 25, 19))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/seta_proximo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Forward.setIcon(icon2)
        self.btn_Forward.setObjectName("btn_Forward")
        self.textBrowser = QtWidgets.QTextBrowser(self.tabCode)
        self.textBrowser.setGeometry(QtCore.QRect(10, 310, 431, 51))
        self.textBrowser.setObjectName("textBrowser")
        self.btnBack = QtWidgets.QToolButton(self.tabCode)
        self.btnBack.setGeometry(QtCore.QRect(10, 10, 25, 19))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/seta_anterior.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBack.setIcon(icon3)
        self.btnBack.setObjectName("btnBack")
        self.btnStop = QtWidgets.QToolButton(self.tabCode)
        self.btnStop.setGeometry(QtCore.QRect(41, 10, 25, 19))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStop.setIcon(icon4)
        self.btnStop.setObjectName("btnStop")
        self.line = QtWidgets.QFrame(self.tabCode)
        self.line.setGeometry(QtCore.QRect(306, 40, 20, 261))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tabCode)
        self.textBrowser_2.setGeometry(QtCore.QRect(330, 40, 111, 261))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.tabWidget.addTab(self.tabCode, "")
        self.tabManual = QtWidgets.QWidget()
        self.tabManual.setObjectName("tabManual")
        self.groupBox = QtWidgets.QGroupBox(self.tabManual)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 351, 211))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.dialLinearSpeed = QtWidgets.QDial(self.groupBox)
        self.dialLinearSpeed.setGeometry(QtCore.QRect(-10, 20, 161, 131))
        self.dialLinearSpeed.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dialLinearSpeed.setMaximum(100)
        self.dialLinearSpeed.setObjectName("dialLinearSpeed")
        self.labelLinearSpeed = QtWidgets.QLabel(self.groupBox)
        self.labelLinearSpeed.setGeometry(QtCore.QRect(-10, 150, 161, 20))
        self.labelLinearSpeed.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelLinearSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLinearSpeed.setObjectName("labelLinearSpeed")
        self.btnRight = QtWidgets.QPushButton(self.groupBox)
        self.btnRight.setGeometry(QtCore.QRect(280, 80, 51, 51))
        self.btnRight.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnRight.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/seta_leste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRight.setIcon(icon5)
        self.btnRight.setIconSize(QtCore.QSize(48, 48))
        self.btnRight.setObjectName("btnRight")
        self.btnUp = QtWidgets.QPushButton(self.groupBox)
        self.btnUp.setGeometry(QtCore.QRect(230, 30, 51, 51))
        self.btnUp.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnUp.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/seta_norte.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUp.setIcon(icon6)
        self.btnUp.setIconSize(QtCore.QSize(48, 48))
        self.btnUp.setObjectName("btnUp")
        self.btnLeft = QtWidgets.QPushButton(self.groupBox)
        self.btnLeft.setGeometry(QtCore.QRect(180, 80, 51, 51))
        self.btnLeft.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnLeft.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/seta_oeste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLeft.setIcon(icon7)
        self.btnLeft.setIconSize(QtCore.QSize(48, 48))
        self.btnLeft.setObjectName("btnLeft")
        self.btnDown = QtWidgets.QPushButton(self.groupBox)
        self.btnDown.setGeometry(QtCore.QRect(230, 130, 51, 51))
        self.btnDown.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnDown.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/seta_sul.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDown.setIcon(icon8)
        self.btnDown.setIconSize(QtCore.QSize(48, 48))
        self.btnDown.setObjectName("btnDown")
        self.lineLinearSpeed = QtWidgets.QLineEdit(self.groupBox)
        self.lineLinearSpeed.setGeometry(QtCore.QRect(94, 180, 31, 21))
        self.lineLinearSpeed.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineLinearSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.lineLinearSpeed.setObjectName("lineLinearSpeed")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 71, 21))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabManual)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 230, 211, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.dialClawSpeed = QtWidgets.QDial(self.groupBox_2)
        self.dialClawSpeed.setGeometry(QtCore.QRect(20, 10, 101, 91))
        self.dialClawSpeed.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dialClawSpeed.setMaximum(100)
        self.dialClawSpeed.setObjectName("dialClawSpeed")
        self.btnClawCw = QtWidgets.QPushButton(self.groupBox_2)
        self.btnClawCw.setGeometry(QtCore.QRect(140, 30, 41, 41))
        self.btnClawCw.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnClawCw.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/seta_horario.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClawCw.setIcon(icon9)
        self.btnClawCw.setIconSize(QtCore.QSize(40, 35))
        self.btnClawCw.setObjectName("btnClawCw")
        self.btnClawCcw = QtWidgets.QPushButton(self.groupBox_2)
        self.btnClawCcw.setGeometry(QtCore.QRect(140, 100, 41, 41))
        self.btnClawCcw.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnClawCcw.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/seta_antihorario.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClawCcw.setIcon(icon10)
        self.btnClawCcw.setIconSize(QtCore.QSize(40, 35))
        self.btnClawCcw.setObjectName("btnClawCcw")
        self.labelClawSpeed = QtWidgets.QLabel(self.groupBox_2)
        self.labelClawSpeed.setGeometry(QtCore.QRect(10, 100, 121, 20))
        self.labelClawSpeed.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelClawSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.labelClawSpeed.setObjectName("labelClawSpeed")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(140, 75, 41, 21))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineClaw = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineClaw.setGeometry(QtCore.QRect(80, 130, 31, 21))
        self.lineClaw.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineClaw.setAlignment(QtCore.Qt.AlignCenter)
        self.lineClaw.setObjectName("lineClaw")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(6, 130, 71, 21))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabManual)
        self.groupBox_3.setGeometry(QtCore.QRect(230, 230, 211, 161))
        self.groupBox_3.setObjectName("groupBox_3")
        self.dialBaseSpeed = QtWidgets.QDial(self.groupBox_3)
        self.dialBaseSpeed.setGeometry(QtCore.QRect(20, 10, 101, 91))
        self.dialBaseSpeed.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dialBaseSpeed.setMaximum(100)
        self.dialBaseSpeed.setObjectName("dialBaseSpeed")
        self.btnBaseCw = QtWidgets.QPushButton(self.groupBox_3)
        self.btnBaseCw.setGeometry(QtCore.QRect(140, 30, 41, 41))
        self.btnBaseCw.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnBaseCw.setText("")
        self.btnBaseCw.setIcon(icon9)
        self.btnBaseCw.setIconSize(QtCore.QSize(40, 35))
        self.btnBaseCw.setObjectName("btnBaseCw")
        self.btnBaseCcw = QtWidgets.QPushButton(self.groupBox_3)
        self.btnBaseCcw.setGeometry(QtCore.QRect(140, 100, 41, 41))
        self.btnBaseCcw.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnBaseCcw.setText("")
        self.btnBaseCcw.setIcon(icon10)
        self.btnBaseCcw.setIconSize(QtCore.QSize(40, 35))
        self.btnBaseCcw.setObjectName("btnBaseCcw")
        self.labelBaseSpeed = QtWidgets.QLabel(self.groupBox_3)
        self.labelBaseSpeed.setGeometry(QtCore.QRect(10, 100, 121, 20))
        self.labelBaseSpeed.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelBaseSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBaseSpeed.setObjectName("labelBaseSpeed")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(140, 70, 41, 31))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 71, 21))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.lineBase = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineBase.setGeometry(QtCore.QRect(84, 130, 31, 21))
        self.lineBase.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineBase.setAlignment(QtCore.Qt.AlignCenter)
        self.lineBase.setObjectName("lineBase")
        self.sliderTemperature = QtWidgets.QSlider(self.tabManual)
        self.sliderTemperature.setGeometry(QtCore.QRect(400, 50, 22, 141))
        self.sliderTemperature.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sliderTemperature.setMaximum(100)
        self.sliderTemperature.setOrientation(QtCore.Qt.Vertical)
        self.sliderTemperature.setObjectName("sliderTemperature")
        self.Temperatura = QtWidgets.QLabel(self.tabManual)
        self.Temperatura.setGeometry(QtCore.QRect(370, 20, 81, 20))
        self.Temperatura.setAlignment(QtCore.Qt.AlignCenter)
        self.Temperatura.setObjectName("Temperatura")
        self.labelTemperature = QtWidgets.QLabel(self.tabManual)
        self.labelTemperature.setGeometry(QtCore.QRect(386, 200, 51, 16))
        self.labelTemperature.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTemperature.setObjectName("labelTemperature")
        self.tabWidget.addTab(self.tabManual, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 477, 21))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionSalvar = QtWidgets.QAction(MainWindow)
        self.actionSalvar.setObjectName("actionSalvar")
        self.actionSalvar_como = QtWidgets.QAction(MainWindow)
        self.actionSalvar_como.setObjectName("actionSalvar_como")
        self.menuArquivo.addAction(self.actionAbrir)
        self.menuArquivo.addAction(self.actionSalvar)
        self.menuArquivo.addAction(self.actionSalvar_como)
        self.menubar.addAction(self.menuArquivo.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ixtopôr"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Gothic\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.btnPlayPause.setToolTip(_translate("MainWindow", "<html><head/><body><p>Play/Pause</p></body></html>"))
        self.btnPlayPause.setText(_translate("MainWindow", "..."))
        self.btn_Forward.setToolTip(_translate("MainWindow", "<html><head/><body><p>Próximo</p></body></html>"))
        self.btn_Forward.setText(_translate("MainWindow", "..."))
        self.btnBack.setToolTip(_translate("MainWindow", "<html><head/><body><p>Anterior</p></body></html>"))
        self.btnBack.setText(_translate("MainWindow", "..."))
        self.btnStop.setToolTip(_translate("MainWindow", "<html><head/><body><p>Parar</p></body></html>"))
        self.btnStop.setText(_translate("MainWindow", "..."))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Gothic\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#ff0000;\">COMANDOS:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">  MOV X VAL</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">  MOV Y VAL</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">  ROT B VAL</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">  ROT G VAL</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">  VEL XY VAL</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">  VEL B VAL</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">  VEL G VAL</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">  DO</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">  ROTINA:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">  ESR ROTINA</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">  FSR ROTINA</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCode), _translate("MainWindow", "Código"))
        self.groupBox.setToolTip(_translate("MainWindow", "Avanço Linear"))
        self.groupBox.setTitle(_translate("MainWindow", "Avanço Linear"))
        self.dialLinearSpeed.setToolTip(_translate("MainWindow", "<html><head/><body><p>Velocidade</p></body></html>"))
        self.labelLinearSpeed.setText(_translate("MainWindow", "0 mm/min"))
        self.lineLinearSpeed.setText(_translate("MainWindow", "10"))
        self.label_5.setText(_translate("MainWindow", "Avanço (mm):"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Garra"))
        self.labelClawSpeed.setText(_translate("MainWindow", "0 º/min"))
        self.label.setText(_translate("MainWindow", "A/S"))
        self.lineClaw.setText(_translate("MainWindow", "90"))
        self.label_3.setText(_translate("MainWindow", "Avanço (º):"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Base"))
        self.labelBaseSpeed.setText(_translate("MainWindow", "0 º/min"))
        self.label_2.setText(_translate("MainWindow", "Z/X"))
        self.label_4.setText(_translate("MainWindow", "Avanço (º):"))
        self.lineBase.setText(_translate("MainWindow", "90"))
        self.Temperatura.setText(_translate("MainWindow", "Temperatura"))
        self.labelTemperature.setText(_translate("MainWindow", "0%"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabManual), _translate("MainWindow", "Manual"))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo"))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir..."))
        self.actionSalvar.setText(_translate("MainWindow", "Salvar"))
        self.actionSalvar_como.setText(_translate("MainWindow", "Salvar como..."))

